### ISSUE TITLE
[Bug] Mobile indicators not really match the true colors

### ISSUE THREAD

**Issue by AngelAsukii** [GriefMoDz/better-status-indicators#12]
Look :

![image_2021-03-29_065107](https://user-images.githubusercontent.com/42059981/112788416-24472c80-905b-11eb-8412-e242070eac5a.png)

**Comment by GriefMoDz** [comment]
I'll take it that you're using "Amazing Activity Cards" as one of your custom themes? If so, the reason behind the mobile indicator not matching the true color of a user's status is due to the fact that it overrides the currently applied styling (i.e. it sets it back to the same color as `online`).
