### ISSUE TITLE
TypeError: Cannot read property 'breadcrumbs' of null

### ISSUE THREAD

**Issue by milanmdev** [GriefMoDz/better-status-indicators#40]
On the plugin settings page, the panel displays the following error:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/29466935/153998625-97ed2eaf-6486-4123-b8f1-f3fc612a6913.png">

Powercord Revision [12de9dc](https://github.com/powercord-org/powercord/commit/12de9dc6c8c35cec730d134731e8cb7c282f0899)

**Comment by GriefMoDz** [comment]
This should've been resolved as of version `1.14.6` (https://github.com/GriefMoDz/better-status-indicators/commit/a403afaef7e207896a75e1ac10083d721d6344a3). Let me know if it otherwise isn't and I shall preform some further diagnostics. Cheers!
