### ISSUE TITLE
[Bug] Discord crashes upon going into a channel

### ISSUE THREAD

**Issue by spinfal** [GriefMoDz/better-status-indicators#41]
The only error I get in console:
![DevTools error image](https://cdn.spin.rip/r/4c554ac7-7af0-4dcb-ae5e-8a8355a779a0.png)

Platform info:
- Canary 123387 (14782d3)
- Host 1.0.45
- Windows 11 (21H2, 22000.556)
- Powercord v2 (29fab9e)

I have tried reinstalling the plugin, and I even removed the plugin to see if the console error shows up without the plugin but it didn't.
This plugin used to work completely fine up until this recent Discord update.

**Comment by GriefMoDz** [comment]
Hey, thanks for the bug report! I've managed to correct this under version 1.15.4 (https://github.com/GriefMoDz/better-status-indicators/commit/2e61acf7a7aba6ad68a6da75746f28f51c2775fd). Let me know if it still isn't working and I shall preform some further diagnostics. Cheers!
